### ISSUE TITLE
How to set breakpoint for specific smali file and specific?

### ISSUE THREAD

**Issue by jmhIcoding** [gast04/JDB-plus-plus#3]
Hello, I have reversed the target android app with apktool, 
and now I want to set breakpoint for a specific smali file : E:\JDB-plus-plus\src\com.steelkiwi.bvpn2\smali\com\steelkiwi\wasel and line 100; 
but I do not know how set breakpoint.

**Comment by gast04** [comment]
Hi,
setting a breakpoint per file is not a thing, but as every file consists of a class you can set a breakpoint
in the class at line 100, which is the same thing.

you can do this either by setting the breakpoint in the .jdbrc file like:
`stop at <yourclass>:100` or by an active debugging session `bp 100`, however this requires 
that the current debugging session is in your target class
